- name: Setup Litestream
  hosts: feedgenerator
  tasks:
    - name: Install Litestream
      ansible.builtin.apt:
        deb: https://github.com/benbjohnson/litestream/releases/download/v0.3.13/litestream-v0.3.13-linux-amd64.deb
    - name: Setup Caddy
      ansible.builtin.template:                                                                                                                     
        src: ./litestream.yml.template
        dest: /etc/litestream.yml
        mode: '0444'
    - name: Start Litestream
      ansible.builtin.service:
        name: litestream
        enabled: yes
        daemon_reload: true
        state: restarted